/**
 * Provider-independent types. Grok / Ring only ever sees these shapes.
 */

export type ProviderName = "bland" | "xai" | "openai_live" | "mock";

export interface Authority {
  may_schedule: boolean;
  may_reschedule: boolean;
  may_cancel: boolean;
  may_accept_terms: boolean;
  may_authorize_amount_up_to: number | null;
  may_authorize_repairs: boolean;
  may_provide_payment_card: boolean;
  /** Facts the agent is allowed to disclose, e.g. "date of birth", "home address". */
  may_disclose: string[];
}

export const DEFAULT_AUTHORITY: Authority = {
  may_schedule: true,
  may_reschedule: true,
  may_cancel: false,
  may_accept_terms: false,
  may_authorize_amount_up_to: null,
  may_authorize_repairs: false,
  may_provide_payment_card: false,
  may_disclose: [],
};

/** Task-scoped call envelope. Generated by the chief of staff. Never the full personal KB. */
export interface CallEnvelope {
  objective: string;
  identity: { owner_name: string; role: string };
  relevant_context: Record<string, unknown>;
  preferences: Record<string, unknown>;
  authority: Authority;
  required_outputs: string[];
}

/** Input to phone.make_call (provider-independent). */
export interface MakeCallRequest {
  recipient_name: string;
  /** E.164 */
  phone_number: string;
  objective: string;
  relevant_context?: Record<string, unknown>;
  preferences?: Record<string, unknown>;
  authority?: Partial<Authority>;
  required_outputs: string[];
  opening_instruction?: string;
  preferred_voice?: string;
  max_duration_seconds?: number;
  provider?: ProviderName;
  /** Caller-supplied idempotency key. Same key => same task, no second dial. */
  idempotency_key?: string;
}

export type CallState =
  | "queued"
  | "dialing"
  | "ringing"
  | "in_progress"
  | "on_hold"
  | "needs_user"
  | "completed"
  | "failed"
  | "cancelled";

export type ResultStatus = "success" | "partial" | "failed" | "needs_user";

export interface CallStatus {
  task_id: string;
  call_id: string | null;
  provider: ProviderName;
  state: CallState;
  started_at: string | null;
  ended_at: string | null;
  duration_seconds: number | null;
  human_answered: boolean | null;
  voicemail: boolean | null;
  intervention_required: boolean;
  /** Present when state === needs_user and the agent is holding for an answer. */
  pending_question: PendingQuestion | null;
  error: string | null;
}

export interface PendingQuestion {
  id: string;
  question: string;
  options?: string[];
  asked_at: string;
}

export interface FollowUp {
  action: string;
  by_whom: "brian" | "business" | "assistant";
  due?: string | null;
  contact?: string | null;
}

export interface NormalizedResult {
  task_id: string;
  status: ResultStatus;
  summary: string;
  human_or_business_reached: string;
  results: Record<string, unknown>;
  commitments_made: string[];
  financial_commitments: string[];
  dates_and_times: string[];
  confirmation_numbers: string[];
  follow_up_required: boolean;
  follow_up: FollowUp | null;
  questions_for_brian: string[];
  duration_seconds: number;
  transcript: string;
  recording_reference: string | null;
  provider: ProviderName;
  raw_provider_result: Record<string, unknown>;
}

/** What a provider returns when the call finishes (before/after extraction). */
export interface ProviderCallOutcome {
  call_id: string;
  ended: boolean;
  state: CallState;
  human_answered: boolean | null;
  voicemail: boolean | null;
  duration_seconds: number | null;
  transcript: string;
  transcript_turns: TranscriptTurn[];
  recording_reference: string | null;
  error: string | null;
  cost_usd: number | null;
  /** Provider-side structured extraction, if the provider produced one (Bland summary, xAI tool call). */
  provider_extraction: Partial<NormalizedResult> | null;
  raw: Record<string, unknown>;
}

export interface TranscriptTurn {
  speaker: "assistant" | "human" | "system";
  text: string;
  at?: string | null;
}

export interface StartCallInput {
  task_id: string;
  envelope: CallEnvelope;
  recipient_name: string;
  phone_number: string;
  opening_instruction?: string;
  preferred_voice?: string;
  max_duration_seconds: number;
  idempotency_key: string;
}

export interface StartCallResult {
  call_id: string;
  state: CallState;
  raw?: Record<string, unknown>;
}

/**
 * The provider interface. Add Retell later by implementing this; nothing above it changes.
 */
export interface PhoneProvider {
  readonly name: ProviderName;
  startCall(input: StartCallInput): Promise<StartCallResult>;
  /** Poll or read cached state. Must be cheap and safe to call repeatedly. */
  getOutcome(call_id: string): Promise<ProviderCallOutcome>;
  cancelCall(call_id: string): Promise<{ cancelled: boolean; message?: string }>;
  /** Optional: answer a pending needs_user question while the call is held open. */
  answerQuestion?(call_id: string, question_id: string, answer: string): Promise<{ delivered: boolean; message?: string }>;
}

export interface CallRecord {
  task_id: string;
  call_id: string | null;
  provider: ProviderName;
  idempotency_key: string;
  request: MakeCallRequest;
  envelope: CallEnvelope;
  status: CallStatus;
  result: NormalizedResult | null;
  events: CallEvent[];
  created_at: string;
  updated_at: string;
}

export interface CallEvent {
  at: string;
  type: string;
  data?: Record<string, unknown>;
}
